# Generated by Django 2.1.7 on 2019-03-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190315_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(default=''),
        ),
    ]
